version: '2'
services:
  mysql-db:
    image: "mysql:latest"
    container_name: "import_mysql"
    volumes:
      - "mysql_data:/var/lib/mysql"
      - "./dump:/var/lib/mysql/dump"
    ports:
      - "43306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fts
    networks:
      - fts
  postgres-db:
    image: "postgres:latest"
    container_name: "import_postgres"
    volumes:
      - "psql_data:/var/lib/postgresql"
      - "./dump:/var/lib/postgresql/data/dump"
    ports:
      - "45432:5432"
    environment:
      POSTGRES_DB: fts
    networks:
      - fts
  elasticsearch:
    image: "elasticsearch:latest"
    ports:
      - "49200:9200"
      - "49300:9300"
    networks:
      - fts
  sphinx:
    image: "romeoz/docker-sphinxsearch:latest"
    ports:
      - "49306:9306"
      - "49312:9312"
    networks:
      - fts
  solr:
    image: "solr:latest"
    ports:
      - "48983:8983"
    networks:
      - fts
  mroonga:
    image: "groonga/mroonga"
    ports:
      - "46603:3306"
  python:
    image: "python:onbuild"
    volumes:
      - "./import:/import"
      - "./dump:/dump"
    networks:
      - fts

volumes:
  mysql_data:
  psql_data:

networks:
  fts: